### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mbehrle** [openlabs/trytond-sale-channel#20]
Getting this error regularly, but don't know yet why. Could be due to some lost context or similar on function fields...

```
Traceback (most recent call last):
  File "/trytond/protocols/jsonrpc.py", line 150, in _marshaled_dispatch
    response['result'] = dispatch_method(method, params)
  File "/trytond/protocols/jsonrpc.py", line 179, in _dispatch
    res = dispatch(*args)
  File "/trytond/protocols/dispatcher.py", line 161, in dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/res/user.py", line 360, in get_preferences
    preferences = cls._get_preferences(user, context_only=context_only)
  File "/trytond/modules/company/company.py", line 171, in _get_preferences
    context_only=context_only)
  File "/trytond/res/user.py", line 325, in _get_preferences
    res[field] = [x.id for x in getattr(user, field)]
  File "/trytond/model/fields/field.py", line 213, in __get__
    return inst.__getattr__(self.name)
  File "/trytond/model/modelstorage.py", line 1311, in __getattr__
    read_data = self.read(list(ids), ffields.keys())
  File "/trytond/modules/company/company.py", line 220, in read
    result = super(User, cls).read(ids, fields_names=fields_names)
  File "/trytond/model/modelsql.py", line 645, in read
    getter_results = field.get(ids, cls, field_list, values=result)
  File "/trytond/model/fields/function.py", line 86, in get
    return dict((name, call(name)) for name in names)
  File "/trytond/model/fields/function.py", line 86, in <genexpr>
    return dict((name, call(name)) for name in names)
  File "/trytond/model/fields/function.py", line 80, in call
    return dict((r.id, method(r, name)) for r in records)
  File "/trytond/model/fields/function.py", line 80, in <genexpr>
    return dict((r.id, method(r, name)) for r in records)
  File "/trytond/modules/sale_channel/user.py", line 59, in get_allowed_channels
    sale_admin = Group.search([('name', '=', 'Sales Administrator')])[0]
IndexError: list index out of range
```

**Comment by tarunbhardwaj** [comment]
Yes this issue will be there with different language. this should be replaced by xml id

**Comment by tarunbhardwaj** [comment]
Fixed in GH-21

**Comment by tarunbhardwaj** [comment]
@mbehrle  this issue has been fixed in #21

**Comment by tarunbhardwaj** [comment]
Released in [3.4.1.2](https://github.com/openlabs/trytond-sale-channel/releases/tag/3.4.1.2)

@mbehrle thanks for reporting the issue.

**Comment by CristhianNY** [comment]
Hi i have the same wrong 

what can I do ?  please

**Comment by tarunbhardwaj** [comment]
@CristhianNY can you please make sure, that you are using latest version of the module.

**Comment by CristhianNY** [comment]
I have gnuhealth 2.8 

when I try generate evaluation say  Traceback (most recent call last):
  File "/trytond/protocols/jsonrpc.py", line 150, in _marshaled_dispatch
    response['result'] = dispatch_method(method, params) ....

and when I enter like a Doctor :/
